### ISSUE TITLE
Can't initialize when integration already exists

### ISSUE THREAD

**Issue by miki2826** [eliranmal/git-flux#22]
<img width="456" alt="screen shot 2017-02-01 at 11 17 21" src="https://cloud.githubusercontent.com/assets/5138735/22501253/ac7f5d3a-e870-11e6-82b0-82a1622d0168.png">

**Comment by eliranmal** [comment]
cleaning git-config stuff should resolve it

**Comment by eliranmal** [comment]
fixed by not pushing to the remote if already exist
