### ISSUE TITLE
Issue in git flux review (Git Bash)

### ISSUE THREAD

**Issue by TomerSH17** [eliranmal/git-flux#59]
While using Git Bash to run git flux review, getting error:

$ git flux team review cmfe

 ➤ type in your github user name: tomers

 ➤ type in your github password:

   creating an access token on 'lpgithub.dev.lprnd.net'...
    ✔ created ok
   creating pull-request from 'team/cmfe' to 'integration'...
sed: -e expression #1, char 2: invalid usage of line address 0
sed: -e expression #1, char 2: invalid usage of line address 0
    ✘ create failed: 'missing_field'

**Comment by eliranmal** [comment]
closing as cannot reproduce
